[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D WIFI_SSID='"YOUR_WIFI_SSID"'
    -D WIFI_PASSWORD='"YOUR_WIFI_PASSWORD"'
    -D BACKEND_IP='"127.0.0.1"'
    -D BACKEND_PORT=8000
    -D USER_EMAIL='"demo@example.com"'
    -D USER_PASSWORD='"YOUR_ACCOUNT_PASSWORD"'
    -D DATA_COLLECTION_MODE=0
    -D HTTP_TIMEOUT_MS=10000
    -D HTTP_CONNECT_TIMEOUT_MS=10000
build_src_filter =
    +<*>
    -<oled_test/>
    -<i2c_diag/>

upload_protocol = esptool
upload_port = COM3
lib_deps =
    bblanchon/ArduinoJson@^7.2.2
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2
    adafruit/Adafruit GFX Library@^1.12.5
    adafruit/Adafruit SSD1306@^2.5.16